---
- debug: var=proxy_env
  when: debug_enabled_default | bool

#Upgrade and reboot Ubuntu/Debian based servers
- name: apt | Upgrade packages
  apt:
    state: latest
    upgrade: dist
    update_cache: yes
  environment: "{{proxy_env}}"
  when: ansible_os_family == "Debian" and update_default | bool

- name: apt | Check if reboot is needed because kernel was upgraded
  stat:
    path: /var/run/reboot-required
  register: apt_reboot_hint_result
  when: ansible_os_family == "Debian"

- set_fact:
    reboot_hint_result: false
  when: ansible_os_family == "Debian" and reboot_default | bool and apt_reboot_hint_result.stat.exists == false

- set_fact:
    reboot_hint_result: true
  when: ansible_os_family == "Debian" and reboot_default | bool and apt_reboot_hint_result.stat.exists == true

- name: apt | restart server
  shell: sleep 3 && shutdown -r now "Reboot required (via Ansible)"
  async: 1
  poll: 0
  ignore_errors: true
  become: yes
  when: ansible_os_family == "Debian" and reboot_default | bool and reboot_hint_result | bool

#Upgrade and reboot Redhat/CentOS based servers
- block:
  - name: yum | Upgrade packages
    yum:
      name: '*'
      state: latest
      update_cache: yes
    environment: "{{proxy_env}}"
    register: stat_yum_upgrade_results
    until: '"failed" not in stat_yum_upgrade_results'
    retries: 2
    delay: 30
  rescue:
  - debug: msg='YUM Upgrade failed'
  - meta: flush_handlers
  - fail: msg='YUM Upgrade failed'
  when: ansible_os_family == "RedHat" and update_default | bool

- name: yum | Check if reboot is needed because kernel was upgraded
  shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
  changed_when: false
  register: yum_reboot_hint_result
  when: ansible_os_family == "RedHat"

- set_fact:
    reboot_hint_result: false
  when: ansible_os_family == "RedHat" and reboot_default | bool and yum_reboot_hint_result.stdout.find("no") != -1

- set_fact:
    reboot_hint_result: true
  when: ansible_os_family == "RedHat" and reboot_default | bool and yum_reboot_hint_result.stdout.find("reboot") != -1

- name: yum | restart server
  command: /usr/bin/systemd-run --on-active=5 --timer-property=AccuracySec=100ms /usr/bin/systemctl reboot
  async: 0
  poll: 0
  ignore_errors: true
  become: yes
  when: ansible_os_family == "RedHat" and reboot_default | bool and yum_reboot_hint_result.stdout.find("reboot") != -1

# Wait for server to come back online
- name: wait for server {{ ansible_ssh_host | default(inventory_hostname) }} to come back online
  wait_for:
    port: "{{ server_upgrade_ssh_port }}"
    state: started
    host: '{{ ansible_ssh_host | default(inventory_hostname) }}'
    delay: 10
    sleep: 2
    timeout: 300
    search_regex: OpenSSH
  become: no
  connection: local
  when: server_upgrade_reboot_wait | bool and reboot_default | bool and reboot_hint_result | bool

